// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIUq7gcEtK0bRVXegwv5NOcW9Lb7JPSr8',
    appId: '1:738905391183:web:c2e08c9c80c5d488f36a3a',
    messagingSenderId: '738905391183',
    projectId: 'wally-mart-f722a',
    authDomain: 'wally-mart-f722a.firebaseapp.com',
    storageBucket: 'wally-mart-f722a.appspot.com',
    measurementId: 'G-GVK3T6YQZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK3kuj_wCGldIxmqcSomgh6XlyimJ7xrw',
    appId: '1:738905391183:android:53cbf4252d8d6205f36a3a',
    messagingSenderId: '738905391183',
    projectId: 'wally-mart-f722a',
    storageBucket: 'wally-mart-f722a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGMdojildE1f1EFJLQol21sUAW8-bhxTo',
    appId: '1:738905391183:ios:a3af8de1d76a31ddf36a3a',
    messagingSenderId: '738905391183',
    projectId: 'wally-mart-f722a',
    storageBucket: 'wally-mart-f722a.appspot.com',
    iosClientId: '738905391183-tsl7ofqdvi2efjbu5mrh7jcr0n7d0a6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaperMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGMdojildE1f1EFJLQol21sUAW8-bhxTo',
    appId: '1:738905391183:ios:a3af8de1d76a31ddf36a3a',
    messagingSenderId: '738905391183',
    projectId: 'wally-mart-f722a',
    storageBucket: 'wally-mart-f722a.appspot.com',
    iosClientId: '738905391183-tsl7ofqdvi2efjbu5mrh7jcr0n7d0a6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaperMart',
  );
}
